version: '3.8'

services:
  app:
    build: .
    container_name: php_apache_app
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app.zip:/var/www/html/app.zip
    depends_on:
      - app
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
